// Generated by scripts/build-knowledge.cjs.
window.knowledgePages = [
  {
    "name": "Private IPv4 & NAT",
    "url": "index.html#note-private-addressing",
    "type": "Concept",
    "keywords": "Networking Concept study A private IP identifies a device inside a network. NAT lets devices using private addresses communicate through an internet-facing address. ",
    "slug": "private-addressing",
    "category": "Networking",
    "question": "Do a staff VLAN and a guest VLAN need separate public IP addresses?",
    "answer": "No. They can use different private subnets and share a public address through PAT. Their separation depends on VLAN configuration and the rules controlling traffic between them, not on having different public IPs."
  },
  {
    "name": "Subnetting",
    "url": "index.html#note-subnetting",
    "type": "Concept",
    "keywords": "Networking Practiced calculations Subnetting divides an IP address range into smaller networks. The subnet mask tells a device which addresses are local and which need a router. ",
    "slug": "subnetting",
    "category": "Networking",
    "question": "Find the network, broadcast, mask, and ordinary usable capacity of 172.19.155.200/18.",
    "answer": "The mask is 255.255.192.0. The increment is 64 in the third octet, so 155 sits in 128–191. Network: 172.19.128.0. Broadcast: 172.19.191.255. Usable range: 172.19.128.1–172.19.191.254, giving 16,382 addresses."
  },
  {
    "name": "VLSM",
    "url": "index.html#note-vlsm",
    "type": "Concept",
    "keywords": "Networking Practiced calculations Variable Length Subnet Masking gives each subnet a size that fits its needs, instead of giving every department the same-sized block. ",
    "slug": "vlsm",
    "category": "Networking",
    "question": "Why can’t 50 engineering devices use a /27, and what else should you count before choosing a /26?",
    "answer": "A /27 has only 30 ordinary usable addresses. A /26 has 62. Count the gateway, other infrastructure, and expected growth as well as the 50 devices. Ensure the chosen block starts on a valid boundary and does not overlap another subnet."
  },
  {
    "name": "VLANs",
    "url": "index.html#note-vlans",
    "type": "Concept",
    "keywords": "Networking Concept study A VLAN makes one physical switch behave like several separate local networks. Devices share a local broadcast network only when their ports belong to the same VLAN. ",
    "slug": "vlans",
    "category": "Networking",
    "question": "A guest VLAN exists, but guests can still open the file server. What would you investigate?",
    "answer": "Check that the guest is actually on the guest VLAN, then inspect routing and firewall or ACL rules between guests and servers. Separate VLANs alone do not guarantee a deny policy. Verify the exact service and both allowed and blocked paths."
  },
  {
    "name": "ARP",
    "url": "index.html#note-arp",
    "type": "Concept",
    "keywords": "Networking Concept study ARP finds the MAC address needed to deliver IPv4 traffic to the next device on a local network. For a remote destination, that device is usually your gateway. address resolution protocol MAC Ethernet broadcast cache next hop gateway spoofing poisoning",
    "slug": "arp",
    "category": "Networking",
    "question": "Your laptop sends to a website outside its /24 subnet. Does ARP look up the website’s MAC address or the default gateway’s, and which IP remains inside the packet?",
    "answer": "With the default route selected, ARP resolves the gateway’s local IPv4 address to its MAC. The Ethernet frame goes to that gateway, while the enclosed IP packet still names the website as its destination. A usable cached gateway mapping can avoid a new ARP request."
  },
  {
    "name": "DNS",
    "url": "index.html#note-dns",
    "type": "Concept",
    "keywords": "Networking Scenario study DNS translates names such as portal.example.com into information computers can use, often an IP address. It helps find a destination; it does not establish the connection. ",
    "slug": "dns",
    "category": "Networking",
    "question": "A name resolves to the expected IP, but the website still fails. What has DNS proved?",
    "answer": "It has provided the expected address for that lookup. It has not proved that the service port is reachable, the TLS handshake works, or the application is healthy. Test those separately and compare the scope of affected users."
  },
  {
    "name": "DHCP",
    "url": "index.html#note-dhcp",
    "type": "Concept",
    "keywords": "Networking Concept study DHCP automatically gives a device an IP address and the network settings it needs. The address is borrowed for a lease period, rather than manually typed into every computer. ",
    "slug": "dhcp",
    "category": "Networking",
    "question": "Devices on one new VLAN get 169.254 addresses, while other VLANs work. What would you check?",
    "answer": "Confirm the clients are using DHCP and are on the intended VLAN. Check that VLAN’s scope, available addresses, gateway relay, and path to the DHCP server. A failure limited to one VLAN points toward its configuration or path, though the address alone does not prove the cause."
  },
  {
    "name": "Syslog",
    "url": "index.html#note-syslog",
    "type": "Concept",
    "keywords": "Cloud & telemetry Concept study Syslog is a common way for devices and applications to send event messages to a central place. Instead of opening every firewall or server, an analyst can review their messages together. ",
    "slug": "syslog",
    "category": "Cloud & telemetry",
    "question": "A firewall shows a local informational deny event, but the collector only receives warning and more urgent events. Why is your search empty?",
    "answer": "Informational is severity 6; warning is 4. A threshold that includes only 0–4 excludes that deny. Check the forwarding filter and collection path before concluding that the event did not happen. The sender’s severity is not an analyst’s final threat assessment."
  },
  {
    "name": "EDR, MDR, and XDR",
    "url": "index.html#note-mdr",
    "type": "Concept",
    "keywords": "Security operations Concept study EDR watches devices. XDR brings signals from several security areas together. MDR provides people and processes to investigate and respond using those tools. ",
    "slug": "mdr",
    "category": "Security operations",
    "question": "Why would an organization use SentinelOne and Blackpoint together instead of choosing only one?",
    "answer": "SentinelOne supplies endpoint visibility and response controls. With the supported integration and coverage configured, Blackpoint can provide continuous monitoring, investigation, and response around those alerts and its other evidence. The organization still coordinates business impact, remediation, and follow-up. XDR can add broader correlation across security areas."
  },
  {
    "name": "SIEM",
    "url": "index.html#note-siem",
    "type": "Concept",
    "keywords": "Security operations Concept study A SIEM collects searchable security data from different systems and applies detection rules. It helps an analyst investigate a sequence of events across the environment. ",
    "slug": "siem",
    "category": "Security operations",
    "question": "How can a SIEM contain logs without producing an alert about those logs?",
    "answer": "Collection and detection are separate. The source may be sending events successfully while no enabled rule matches the behavior, its threshold is not reached, or its query looks in the wrong table or time range. Check the raw events before changing the detection."
  },
  {
    "name": "ZTNA / SASE",
    "url": "index.html#note-ztna-sase",
    "type": "Concept",
    "keywords": "Identity & access Concept study ZTNA checks who is requesting access and the conditions of that request before allowing a path to a resource. SASE combines secure access with wider networking and security services. ",
    "slug": "ztna-sase",
    "category": "Identity & access",
    "question": "Why does successful MFA not guarantee that an employee can open a private file share?",
    "answer": "MFA satisfies an authentication requirement. The device and request must also meet the access policy, the private server must be reachable through an approved path, and the user must have permission on the share and files."
  },
  {
    "name": "Email authentication",
    "url": "index.html#note-email-auth",
    "type": "Concept",
    "keywords": "Security operations Scenario study SPF, DKIM, and DMARC help check whether a message is authorized to use a domain. They do not prove that the sender is honest or that the request is safe. ",
    "slug": "email-auth",
    "category": "Security operations",
    "question": "Why can a lookalike domain pass DMARC?",
    "answer": "The attacker can configure valid SPF and DKIM for the domain they own, aligned with that domain’s From address. DMARC checks domain authorization, not whether the domain is the real company or whether the payment request is legitimate."
  },
  {
    "name": "Business email compromise",
    "url": "index.html#note-bec",
    "type": "Concept",
    "keywords": "Security operations Scenario study Business email compromise is a scam that uses a believable business conversation to trick someone into sending money, sharing information, or changing an important process. ",
    "slug": "bec",
    "category": "Security operations",
    "question": "A supplier’s email passes DMARC and asks for new bank details. Is it safe to approve the change?",
    "answer": "No. A compromised supplier mailbox or a lookalike domain can pass authentication. Pause the change, verify it through an existing trusted contact method, and investigate the message and any user interaction. Escalate promptly if money or sensitive information has already been sent."
  },
  {
    "name": "Risky sign-ins",
    "url": "index.html#note-identity",
    "type": "Concept",
    "keywords": "Identity & access Scenario study A risky sign-in is an authentication event with signals that deserve investigation. The signal helps prioritize work; the surrounding evidence determines whether an account is compromised. ",
    "slug": "identity",
    "category": "Identity & access",
    "question": "Two successful sign-ins appear far apart within minutes. What would make you more or less concerned?",
    "answer": "Compare known VPN or proxy use, device and client details, authentication and policy results, and subsequent activity. A user-confirmed VPN with expected behavior may explain the location shift. Unexpected MFA changes, mailbox forwarding, or unfamiliar resource access increase concern and may justify prompt containment under the response plan."
  },
  {
    "name": "Active Directory",
    "url": "index.html#note-windows-domain",
    "type": "Concept",
    "keywords": "Identity & access Concept study Active Directory Domain Services keeps a shared directory of users, computers, and groups. Domain controllers use it to support domain authentication and centralized administration. ",
    "slug": "windows-domain",
    "category": "Identity & access",
    "question": "Does every Windows Server machine validate domain logons?",
    "answer": "No. Windows Server can host many roles. Domain controllers running AD DS provide domain authentication services. A server used only for file sharing or an application is not automatically a domain controller."
  },
  {
    "name": "File shares",
    "url": "index.html#note-file-shares",
    "type": "Concept",
    "keywords": "Identity & access Concept study A file share lets other computers access a folder over the network. The network path finds the server and share; the user’s permissions decide what they can do there. ",
    "slug": "file-shares",
    "category": "Identity & access",
    "question": "Z: disappeared, but the expected UNC path opens successfully. What is your next focus?",
    "answer": "The server path and this user’s basic access work. Investigate the drive mapping, sign-in script, Group Policy, or device-management configuration that should create Z:. Also check whether the problem is limited to one session or device."
  },
  {
    "name": "Windows events",
    "url": "index.html#note-windows-events",
    "type": "Concept",
    "keywords": "Cloud & telemetry Lab application Windows event logs record activity on a computer. Event IDs tell you what kind of event was recorded; the event’s fields explain who, where, when, and how. ",
    "slug": "windows-events",
    "category": "Cloud & telemetry",
    "question": "A 4624 is followed by a 4672 with the same Logon ID on one host. Does that prove privilege escalation?",
    "answer": "No. It shows a successful logon and sensitive privileges assigned to that session. This can be normal for an administrative or system account. Check the account, logon type, source, time, expected role, and subsequent actions to decide whether the activity is suspicious."
  },
  {
    "name": "TLS",
    "url": "index.html#note-tls",
    "type": "Concept",
    "keywords": "Networking Concept study TLS protects data in transit by encrypting it and checking that it has not been changed. In a normal HTTPS connection, it also helps the browser verify the server’s identity. ",
    "slug": "tls",
    "category": "Networking",
    "question": "A site has a valid HTTPS certificate. Does that mean the site’s content is trustworthy?",
    "answer": "No. A valid certificate helps authenticate the connection to that hostname and protect data in transit. An attacker can obtain a valid certificate for a domain they control, and a legitimate site can also be compromised."
  },
  {
    "name": "TCP",
    "url": "index.html#note-tcp",
    "type": "Concept",
    "keywords": "Networking Concept study TCP carries an ordered stream of bytes between two endpoints. It tracks delivery and retransmits missing data so applications do not have to handle ordinary packet loss themselves. ",
    "slug": "tcp",
    "category": "Networking",
    "question": "A TCP segment starts at sequence 1000 and carries 100 data bytes. Is tcp.stream == 1100 the way to find the next bytes?",
    "answer": "No. Sequence 1100 would describe the next data-byte position in this simplified example. tcp.stream is Wireshark’s separate identifier for the whole connection. Filter the right stream, then inspect sequence and acknowledgement numbers inside it."
  },
  {
    "name": "Alert triage",
    "url": "index.html#note-alert-triage",
    "type": "Concept",
    "keywords": "Security operations Concept study Triage means deciding what an alert shows, how urgent it is, and who needs to act next. An alert starts a question; it does not finish an investigation. SOC escalation queue severity priority false positive benign positive",
    "slug": "alert-triage",
    "category": "Security operations",
    "question": "An EDR alert says “isolation requested,” but the device is offline. What can you report?",
    "answer": "Report that isolation was requested and remains unverified. Record the last sensor contact, escalate alternate containment through the response owner, and keep scope open. A requested action is not a completed action."
  },
  {
    "name": "Incident response",
    "url": "index.html#note-incident-response",
    "type": "Concept",
    "keywords": "Security operations Concept study Incident response is the coordinated work of understanding a security incident, limiting harm, restoring trustworthy service, and learning from what happened. containment eradication recovery evidence timeline handoff incident response IR",
    "slug": "incident-response",
    "category": "Security operations",
    "question": "Why does “the device is isolated” not mean “the incident is resolved”?",
    "answer": "Isolation limits a network path. It does not establish the original cause, remove persistence, secure affected accounts, restore service, or validate recovery. Those tasks need their own evidence and owners."
  },
  {
    "name": "Phishing",
    "url": "index.html#note-phishing",
    "type": "Concept",
    "keywords": "Security operations Concept study Phishing uses a deceptive message to persuade someone to reveal information or take an unsafe action. The important question is what the message is trying to make the recipient do. social engineering spear phishing credential harvesting QR smishing vishing reported email",
    "slug": "phishing",
    "category": "Security operations",
    "question": "A message passes DMARC and asks Finance to change a supplier’s bank details. Is it safe to approve?",
    "answer": "No. DMARC concerns authenticated domain alignment, not the truth of the payment instruction. Verify the change through a trusted, independent supplier contact and the established payment process."
  },
  {
    "name": "Malware",
    "url": "index.html#note-malware",
    "type": "Concept",
    "keywords": "Security operations Concept study Malware is software used to cause harm or gain unauthorized access. Investigating it means understanding what ran and what changed, not just recognizing a threatening filename. AV antivirus infection ransomware process tree persistence hash infostealer",
    "slug": "malware",
    "category": "Security operations",
    "question": "Why should you review the process timeline after an antivirus tool quarantines a file?",
    "answer": "Quarantine describes the file’s current handling. The timeline may show that it executed earlier, launched other processes, established persistence, or accessed credentials. Those possibilities require separate investigation."
  },
  {
    "name": "Vulnerability management",
    "url": "index.html#note-vulnerability-management",
    "type": "Concept",
    "keywords": "Security operations Concept study Vulnerability management is the repeated work of finding weaknesses, deciding which matter most, fixing or reducing them, and verifying the result. vulnerability assessment scanning CVE CVSS KEV patching exposure remediation authenticated scan",
    "slug": "vulnerability-management",
    "category": "Security operations",
    "question": "A scanner reports no findings on a server, but authentication failed. What should you conclude?",
    "answer": "The assessment has a coverage gap. Confirm which checks ran, repair authorized scan access, and repeat the relevant assessment. You cannot treat an unauthenticated or unreachable result as proof that the server is patched."
  },
  {
    "name": "Risk",
    "url": "index.html#note-risk",
    "type": "Concept",
    "keywords": "Security operations Concept study Risk describes how a possible event could harm something important and how likely that harm is. It helps a team decide where to spend attention and effort. CIA triad confidentiality integrity availability likelihood impact residual inherent risk assessment",
    "slug": "risk",
    "category": "Security operations",
    "question": "How are a vulnerability and a risk different?",
    "answer": "A vulnerability is a weakness. A risk describes possible harm involving an asset, a threat or event, likelihood, impact, and relevant controls. The same weakness can create different risk in different environments."
  },
  {
    "name": "Security controls",
    "url": "index.html#note-security-controls",
    "type": "Concept",
    "keywords": "Security operations Concept study A security control is a safeguard intended to reduce risk. To know whether it works, you need a clear objective and evidence from the systems and people it covers. preventive detective corrective technical administrative physical least privilege defense in depth control gaps testing",
    "slug": "security-controls",
    "category": "Security operations",
    "question": "Why test a permitted connection as well as a blocked one after a firewall change?",
    "answer": "A control must enforce the intended restriction while preserving required service. A deny-all mistake could pass only the negative test. Together, permitted and denied cases help verify the actual objective."
  },
  {
    "name": "Security awareness",
    "url": "index.html#note-security-awareness",
    "type": "Concept",
    "keywords": "Security operations Concept study Security awareness helps people recognize risky situations and know what to do next. Its value is safer behavior and faster reporting, not just completed training slides. KnowBe4 awareness training phishing simulations culture reporting",
    "slug": "security-awareness",
    "category": "Security operations",
    "question": "Why is a lower simulated-phishing click rate not enough to prove a training program works?",
    "answer": "The result depends on the message, audience, delivery, and security tooling. Also check reporting behavior, response quality, practical decision-making, and whether the organization fixes the problems the exercise reveals."
  },
  {
    "name": "Firewalls",
    "url": "index.html#note-firewalls",
    "type": "Concept",
    "keywords": "Networking Concept study A firewall decides which network traffic is permitted across a boundary. A useful rule describes who can reach what service, in which direction, and why. ACL rule order stateful filtering ports TCP UDP inbound outbound NAT",
    "slug": "firewalls",
    "category": "Networking",
    "question": "A staff allow rule is below a deny-all rule in a first-match policy. Which wins?",
    "answer": "The earlier matching deny wins. The later allow is never reached for that traffic. Place the approved specific allow correctly, then verify both required access and traffic that must remain blocked."
  },
  {
    "name": "Routing",
    "url": "index.html#note-routing",
    "type": "Concept",
    "keywords": "Networking Concept study Routing chooses the next hop for an IP packet. Each router uses its own routing information to move the packet toward its destination. route table next hop default gateway longest prefix match static dynamic OSPF BGP",
    "slug": "routing",
    "category": "Networking",
    "question": "A destination matches both 10.20.0.0/16 and 10.20.30.0/24. Which installed route is selected for 10.20.30.10?",
    "answer": "The /24 route, because it is the longest matching prefix. If it is removed, /16 may become the match, but choosing that path does not prove it can deliver the packet."
  },
  {
    "name": "Switching",
    "url": "index.html#note-switching",
    "type": "Concept",
    "keywords": "Networking Concept study An Ethernet switch learns where devices are connected and forwards frames within a VLAN. It learns from source MAC addresses and looks up destination MAC addresses. switch ports MAC table CAM learning flooding unicast broadcast trunk access STP",
    "slug": "switching",
    "category": "Networking",
    "question": "What does a switch learn when a frame arrives, and how is that different from ARP?",
    "answer": "The switch learns the source MAC on the incoming port and VLAN, then looks up the destination MAC. ARP is a separate IPv4-to-MAC resolution process used by endpoints and routers for local delivery."
  },
  {
    "name": "VPNs",
    "url": "index.html#note-vpns",
    "type": "Concept",
    "keywords": "Networking Concept study A VPN creates a logical connection across another network. In a typical remote-access VPN, an authenticated, encrypted tunnel carries selected traffic between a device and an organization. VPN remote access site to site split tunnel force full tunnel IPsec TLS overlapping subnets",
    "slug": "vpns",
    "category": "Networking",
    "question": "A VPN is connected and a file server answers on TCP 445, but a share returns Access denied. Where should the investigation go next?",
    "answer": "Review the identity used for the share and its share/filesystem permissions. The successful TCP test supports service reachability, not authorization to read files."
  },
  {
    "name": "Troubleshooting",
    "url": "index.html#note-troubleshooting",
    "type": "Concept",
    "keywords": "IT operations Concept study Troubleshooting is a controlled process of narrowing a problem with evidence. Start with what fails, compare what still works, and test one explanation at a time. Windows Windows Server macOS OS support troubleshooting processes services Task Manager Activity Monitor diagnostics",
    "slug": "troubleshooting",
    "category": "IT operations",
    "question": "One user fails on two devices while another authorized user succeeds on both. What does this comparison help you prioritize?",
    "answer": "User-specific identity or permissions become a stronger hypothesis than a device-wide connectivity failure. Review the exact account, group membership, and resource authorization, and verify with an appropriate test."
  },
  {
    "name": "Change management",
    "url": "index.html#note-change-management",
    "type": "Concept",
    "keywords": "IT operations Concept study Change management makes a system change deliberate, reviewable, and recoverable. Success means the intended result works and required services still work afterward. change control rollback maintenance configuration baseline approval emergency change verification",
    "slug": "change-management",
    "category": "IT operations",
    "question": "Why is a configuration backup not always a complete rollback plan?",
    "answer": "You also need a supported restoration method, access to execute it, prerequisites, decision criteria, and validation. If the change disconnects your management session, a backup alone does not restore your ability to reach the device."
  },
  {
    "name": "Technical documentation",
    "url": "index.html#note-technical-documentation",
    "type": "Concept",
    "keywords": "IT operations Concept study Useful technical documentation lets another person understand the evidence or repeat a task without guessing. Its structure should match what that reader needs to do. documentation KB SOP runbook tickets client communication evidence handoff",
    "slug": "technical-documentation",
    "category": "IT operations",
    "question": "What is missing from “we are investigating and will update you soon”?",
    "answer": "It omits confirmed scope or impact, the evidence and action state, the responsible next owner, and a specific achievable update time. Fill those in from the actual case rather than using one universal sentence."
  }
];
