import {useEffect,useRef,useState,useId} from 'react';
import {ChevronDown,Check,Lock,ArrowUpRight} from 'lucide-react';
import {Help} from './help';
export function ShiftDial({wave,total,activeWave,completed,mode,seed,readOnly,onSelect}:{wave:number;total:number;activeWave:number;completed:boolean;mode:string;seed:number;readOnly:boolean;onSelect:(wave:number)=>void}){
 const [open,setOpen]=useState(false),root=useRef<HTMLDivElement>(null),trigger=useRef<HTMLButtonElement>(null),id=useId();
 const status=(n:number)=>n>activeWave?'Locked preview':n<activeWave||completed?'Completed':'Active';
 useEffect(()=>{if(!open)return;const close=(e:PointerEvent)=>{if(!root.current?.contains(e.target as Node))setOpen(false)};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close)},[open]);
 return <div className="shift-dial" ref={root} data-open={open} onPointerEnter={e=>{if(e.pointerType==='mouse')setOpen(true)}} onPointerLeave={e=>{if(e.pointerType==='mouse')setOpen(false)}} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setOpen(false)}} onKeyDown={e=>{
  if(e.key==='Escape'){setOpen(false);trigger.current?.focus();e.stopPropagation()}
  if(['ArrowRight','ArrowLeft','ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();setOpen(true);const buttons=Array.from(root.current?.querySelectorAll<HTMLButtonElement>('.shift-stop')||[]);const index=buttons.indexOf(document.activeElement as HTMLButtonElement);const next=e.key==='Home'?0:e.key==='End'?total-1:index<0?wave-1:(index+(['ArrowRight','ArrowDown'].includes(e.key)?1:total-1))%total;requestAnimationFrame(()=>root.current?.querySelectorAll<HTMLButtonElement>('.shift-stop')[next]?.focus())}
 }}>
  <div className="shift-dial-meta">{mode.toUpperCase()} <span> / {seed}</span><Help topic="modes" label="Modes and seeds"/></div>
  <div className="shift-dial-heading"><span className="shift-word">Shift</span><button ref={trigger} className="shift-number-trigger" aria-label={`Browse shifts, current shift ${wave}`} aria-expanded={open} aria-controls={id} onClick={e=>{if(e.detail===0)setOpen(v=>!v);else if(e.nativeEvent instanceof PointerEvent&&e.nativeEvent.pointerType==='touch')setOpen(v=>!v);else setOpen(true)}}><span className="shift-number" key={wave}>{String(wave).padStart(2,'0')}</span><ChevronDown size={17}/></button><span className="shift-total">/ {String(total).padStart(2,'0')}</span><Help topic="shift" label="Shift progression"/></div>
  <div className="shift-dial-foot"><span className={`shift-status-dot ${status(wave)==='Locked preview'?'is-locked':''}`}/>{status(wave)}{readOnly&&status(wave)!=='Locked preview'?' · Read only':''}<span className="shift-browse-hint">Browse ↗</span></div>
  {open&&<nav className="shift-reel" id={id} aria-label="Shift navigation"><div className="shift-reel-heading"><span>SHIFT ARCHIVE</span><small>Select an assignment</small></div><div className="shift-stops">{Array.from({length:total},(_,i)=>i+1).map(n=><button key={n} className="shift-stop" aria-label={`Shift ${n} ${status(n)}`} aria-pressed={wave===n} onClick={()=>{onSelect(n);setOpen(false);trigger.current?.focus()}}><span className="shift-stop-rail"/><span className="shift-stop-number">{String(n).padStart(2,'0')}</span><span className="shift-stop-state">{status(n)==='Completed'?<Check size={12}/>:status(n)==='Locked preview'?<Lock size={12}/>:<ArrowUpRight size={12}/>} {status(n)}</span><span className="shift-stop-caption">{status(n)==='Completed'?'Review casework':status(n)==='Locked preview'?'Preview briefings':'Open assignment'}</span></button>)}</div><p>Browsing never spends turns or changes progress.</p></nav>}
 </div>
}
