export type ClientUpdate = {text:string;why:string};
// Index 0 is the recommended update; presentation order is shuffled per incident.
const updates:Record<string,[ClientUpdate,ClientUpdate,ClientUpdate]>={
 bec:[{text:'We confirmed unauthorized mailbox activity involving the payment instructions. We are coordinating account containment, tracing affected messages and contacting the payment owner through a trusted channel. Payment recovery and the extent of access still need verification.',why:'Names the confirmed mailbox compromise, coordinates the financial response, and avoids claiming money or data has been recovered.'},{text:'The password change resolves the invoice issue. Finance can continue using the payment details from the email thread.',why:'A password change does not validate payment instructions or remove every persistence mechanism.'},{text:'We will ask the sender in the affected email thread to confirm the new bank details before taking further action.',why:'The compromised thread is not a trustworthy channel for independently verifying payment instructions.'}],
 travel:[{text:'The device, session, corporate VPN address and independent user verification explain the location alert. We can document this as expected VPN activity and preserve access, while keeping other identity detections enabled.',why:'Closes the specific verified benign alert without disabling broader monitoring.'},{text:'The two locations confirm someone stole the account. We need to disable it until the user returns to the office.',why:'The same device and session plus verified corporate VPN use contradict a location-only compromise conclusion.'},{text:'The user recognized the alert, so we can suppress all future impossible-travel alerts for this account.',why:'One verified benign event does not justify suppressing every future alert.'}],
 ransom:[{text:'The evidence indicates malicious file activity on the server. We are coordinating isolation and scoping with incident response, preserving evidence and validating recovery options before restoring service. We cannot yet confirm the full impact.',why:'Treats the malicious activity as an incident and separates containment from validated recovery.'},{text:'The security agent stopped the process, so the server can reconnect immediately and the incident can close.',why:'Stopping one process does not establish scope or safe recovery.'},{text:'We should restore the latest backup directly onto the connected server now to minimize downtime.',why:'Recovery before containment and backup validation can reintroduce risk and destroy useful evidence.'}],
 admin:[{text:'The script and execution context match the approved maintenance change and administrator verification. We can record the activity as authorized and retain monitoring for deviations from that approved scope.',why:'Uses the change record and execution evidence to justify a bounded benign conclusion.'},{text:'PowerShell ran after hours, so this is confirmed malware regardless of the change record.',why:'Time and tool name alone do not outweigh verified authorized execution.'},{text:'Because this script was approved, future PowerShell alerts from this administrator can be ignored.',why:'Approval covers this activity, not every later command or session.'}],
 phish:[{text:'This was a malicious document lure with evidence of account misuse. We are coordinating identity containment, reviewing affected messages and recipients, and checking for persistence. Please use a trusted channel for follow-up while we establish the full scope.',why:'Connects phishing and account misuse to a scoped response without assuming deleting the email fixes the account.'},{text:'We removed the reported message, so the account is safe and no further identity review is needed.',why:'Removing a message does not undo account misuse or persistence.'},{text:'Please open the document again and send us a screenshot of the sign-in screen so we can confirm it.',why:'Re-exposing the user to the malicious link is unnecessary; investigate retained evidence safely.'}],
 training:[{text:'We matched the message to the approved awareness campaign using its campaign record, recipient and timestamp. The reviewed activity supports an authorized simulation. Thank you for reporting it; please continue reporting suspicious messages.',why:'Explains why this report is benign and reinforces useful reporting behavior.'},{text:'The message looked like our training emails, so we marked it as a simulation without needing to match the campaign records.',why:'Appearance alone does not establish an authorized simulation.'},{text:'This was a training email. Please stop reporting similar messages so we can reduce unnecessary tickets.',why:'Discourages future reporting and assumes similar-looking messages will also be benign.'}],
 vuln:[{text:'Gateway B is the priority because it is exposed, its vulnerability is being exploited, and three sites depend on it. We are coordinating the approved management-access restriction and a tested patch with rollback, followed by a rescan and remote-access checks. Exploitation reports alone do not confirm our gateway was breached.',why:'Prioritizes actual exposure and service impact, preserves continuity and distinguishes vulnerability from confirmed compromise.'},{text:'We will patch isolated server A first because its 9.8 score automatically makes it the highest business risk.',why:'CVSS alone misses B’s exposure, exploitation activity and business importance.'},{text:'Active exploitation has been reported, so we can tell all three sites their gateway has definitely been compromised.',why:'Reports of exploitation do not prove compromise of this specific gateway.'}],
 scan:[{text:'The scan cannot support a clean result: authentication failed and only 3 of 24 expected hosts were reached. We are correcting approved scan access and reconciling scope before a controlled rescan, then checking authentication and coverage before reporting findings.',why:'Reports the evidence-quality problem and specifies what makes a rescan trustworthy.'},{text:'The scan completed with no critical findings, so all 24 servers can be reported as low risk.',why:'Job completion is not successful authentication or full coverage.'},{text:'We can remove the scan-source restrictions and use a domain administrator account permanently to ensure future scans work.',why:'Restoring scan access must preserve approved scope and least privilege.'}],
 ztna:[{text:'Access was denied because the Mac did not meet the encryption requirement, despite valid sign-in and group membership. We are coordinating an approved compliant loan device and encryption remediation, then rechecking device compliance and application access. The global security requirement stays enabled.',why:'Explains the actual denial and gives a safe route to productivity without a global bypass.'},{text:'MFA passed, so the access system is malfunctioning. We will disable posture checks for all contractors.',why:'Authentication does not establish device compliance; a global bypass is not authorized.'},{text:'We need to reset the contractor’s password before investigating encryption or device posture.',why:'The evidence identifies device encryption, not failed authentication, as the cause.'}],
 firewall:[{text:'The emergency rule permits more traffic than the application needs. We are coordinating a narrowly scoped replacement with the service owner, a rollback plan and checks of both required access and unwanted traffic before retiring the broad rule.',why:'Addresses excessive access through a tested, scoped change rather than an unplanned outage.'},{text:'The application works now, so the any-any rule can remain as the permanent fix.',why:'Functionality does not justify unrestricted network access.'},{text:'We will delete the emergency rule immediately without checking the application’s dependencies or a rollback plan.',why:'Removing a broad rule without a tested replacement risks avoidable disruption.'}],
 dns:[{text:'The configured DNS resolver could not resolve the internal application; querying the approved internal resolver succeeded. We are restoring the approved DHCP DNS setting, renewing the affected host’s lease and verifying normal name resolution and application access with the user.',why:'Explains the demonstrated DNS cause and includes client-side renewal and validation.'},{text:'The application is reachable by IP, so there is no service issue and the ticket can close.',why:'IP reachability does not mean users can resolve the application name.'},{text:'We will make the external resolver authoritative for the internal application instead of restoring the approved DHCP setting.',why:'That changes the architecture unnecessarily and does not follow the approved rollback.'}],
 oauth:[{text:'We confirmed unauthorized application access to the mailbox. We are revoking the application’s access and affected sessions, preserving consent and access logs, and checking other grants and accessed data. A password reset alone does not remove this access path.',why:'Addresses OAuth consent and observed access, while keeping the extent of data access under review.'},{text:'There was no forwarding rule, so the application did not access email and can remain enabled.',why:'The app accessed the mailbox independently of forwarding rules.'},{text:'We will reset the password and leave the app grant in place because its permissions are unrelated to account access.',why:'The consent grant is an access path that must be addressed explicitly.'}],
 mac:[{text:'The update prompt led to malicious activity on the Mac. We are coordinating endpoint containment, preserving the relevant evidence and removing persistence, with recovery and related account checks before confirming safe return to use.',why:'Treats the fake update as an endpoint incident and separates cleanup from verified recovery.'},{text:'The installer window is closed, so the Mac can be returned to normal use without checking persistence.',why:'Closing the prompt does not remove installed malicious components.'},{text:'We should disable endpoint protection to let the update finish and then check the result.',why:'The evidence indicates a malicious update; weakening protection would increase exposure.'}],
 handoff:[{text:'WS-062 was isolated at 11:02 UTC and threat remediation completed at 11:06. Peer review, scope confirmation and recovery approval remain pending. The user has a loan device; the evening analyst owns the follow-up and the next client update is due at 12:00 UTC.',why:'Separates completed actions from pending validation, names the owner and preserves the actual promised update time.'},{text:'The ticket says fixed, so WS-062 can reconnect and we can assure the client no other devices are affected.',why:'The evidence does not establish safe reconnection or the absence of other affected devices.'},{text:'Remediation completed at 11:06, so no further owner or client update is needed.',why:'Peer review and recovery remain pending and the client is owed a timed update.'}]
};
const resolved:Record<string,string>={
 dns:'The incorrect DHCP DNS setting was restored to the approved internal resolver. We renewed the affected host’s lease and verified internal name resolution and application access with the user. Other affected DHCP clients need the corrected setting through lease renewal; record any remaining affected devices for follow-up.',
 scan:'The rescan followed correction of the approved scan access and scope. Authentication and host coverage were checked before accepting the findings. The original clean result was unreliable; remediation priorities should use the validated results.',
 ztna:'The encryption-related access issue was addressed through the approved compliant-device route and device remediation. Compliance and scoped application access were rechecked; the global posture requirement remains enabled.',
 vuln:'The exposed gateway was prioritized, the approved mitigation and coordinated patch steps were completed, and the rescan and service checks were performed. We are documenting those validation results; exploitation reports alone do not establish that this gateway was breached.',
 firewall:'The broad emergency rule was replaced through the approved scoped change. Required service access and the effectiveness of the restrictions were tested; the change and rollback details are recorded.'
};
export function clientUpdates(c:{template:string;done:string[];reads:number[]},required:string[]):ClientUpdate[]{const choices=updates[c.template];if(!choices)throw Error('Missing client updates: '+c.template);const complete=required.every(id=>c.done.includes(id))&&c.reads.length===3;return choices.map((v,i)=>({...v,text:i===0&&complete&&resolved[c.template]?resolved[c.template]:v.text}));}
export function updateOrder(id:string):number[]{let seed=[...id].reduce((v,c)=>(v*31+c.charCodeAt(0))>>>0,17);const a=[0,1,2];for(let i=2;i>0;i--){seed=(Math.imul(seed,1664525)+1013904223)>>>0;const j=seed%(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;}
