import {useEffect,useLayoutEffect,useId,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
export const explanations={
 turn:'A turn is an action, not elapsed time. Reviewing a new evidence source or attempting a response normally spends one turn. Reading, writing notes, switching tabs, and reopening reviewed evidence are free. Specialties can waive a turn. Practice mode does not advance turns.',
 pressure:'Pressure is urgency for each incident. Each turn adds 4 pressure to the active incident and 3 to others in Guided mode; Veteran adds 7 and 6. Each unstabilized incident at 85+ pressure costs 2 trust per turn. A successful stabilizing action reduces pressure by 25 and stops further growth. Closed incidents stop contributing. Severity labels are fixed scenario labels, separate from pressure.',
 trust:'Client trust starts at 100 for a new run and carries into the next shift. Response mistakes cost 8 trust (5 for Communicator). An incorrect client update costs 8; closing below 60 points costs another 12. Each unstabilized incident at 85+ pressure also costs 2 per turn. Losses add together. Trust is separate from your incident score.',
 intel:'Intel buys between-shift upgrades. Earn 1 intel per full 20 incident points: 100 earns 5, 85 earns 4. Watchtower costs 6 and reduces pressure growth by 1 while active. Client liaison costs 6 and restores 25 trust, capped at 100. You may continue without buying an upgrade.',
 xp:'XP is the sum of points earned from completed incidents. Every 350 XP raises your level. The displayed rank progresses from Apprentice to Sentinel at level 4 and Incident captain at level 8. These are game milestones, not certifications; XP is not spent on upgrades.',
 specialty:'Specialties change perks, not incident selection or correct answers. Investigator: the first evidence review per incident is a free turn. Responder: successful stabilizing actions are free turns. Communicator: response mistakes lose 5 trust instead of 8; the 8-point score penalty still applies. Turn-saving perks add no benefit in Practice mode.',
 shift:'Guided and Veteran runs have three shifts, each with four incidents. Hover, tap, or focus the large shift number and press Enter to browse shifts. Use the shift picker to review completed work or browse future queues and incident tabs. Browsing costs no turns. Future evidence stays collapsed; response and handoff fields remain obscured until unlocked. Close every incident, then scroll to the upgrade panel below the incident area. Choosing an upgrade or Continue without upgrade starts the next shift. After shift 3, return to the loadout for a new run. Completed records stay in Portfolio. Practice has one incident.',
 score:'Each incident offers 100 points: evidence 20, safe response actions 45, correct classification 20, and client update 15. Each response mistake deducts 8. Required action order matters. Notes are saved but not automatically graded. The debrief explains your points and missed steps.',
 modes:'Guided provides coaching and a fixed opening queue. Veteran raises pressure faster and hides coaching during open incidents. Practice focuses on one incident with no advancing turns or pressure. The seed controls repeatable incident ordering and client assignments; your specialty does not choose incidents.',
 navigation:'Operations is where you investigate and respond. Manual explains concepts and scenarios. Mastery & journal shows practice by topic and saved notes. Portfolio collects completed records and offers downloads and backup restore. Selecting an incident in the queue changes the case you are viewing.',
 saving:'Your editable progress saves automatically in this browser. Download progress JSON creates a separate portable backup; it does not trigger autosave or publish anything. Portfolio shows this browser’s records. View khanfarris profile switches to a read-only published snapshot and leaves your own save untouched.',
 win:'The run target is at least 70 trust and an average incident score of 80. You can continue learning after missing the target. Trust reflects queue management; incident scores reflect recorded decisions. Completing a shift unlocks the upgrade choices below the incident area.'
};
export function Help({topic,label}:{topic:keyof typeof explanations;label:string}){
 const [open,setOpen]=useState(false),[position,setPosition]=useState({left:12,top:12,width:300});
 const ref=useRef<HTMLSpanElement>(null),tooltip=useRef<HTMLSpanElement>(null),id=useId();
 function show(){const box=ref.current!.getBoundingClientRect(),width=Math.min(320,innerWidth-24);setPosition({width,left:Math.max(12,Math.min(box.left,innerWidth-width-12)),top:box.bottom});setOpen(true);}
 useLayoutEffect(()=>{if(!open)return;const box=tooltip.current?.getBoundingClientRect();if(box&&box.bottom>innerHeight-12)setPosition(p=>({...p,top:Math.max(12,(ref.current?.getBoundingClientRect().top||innerHeight)-box.height-8)}));},[open]);
 useEffect(()=>{if(!open)return;const dismiss=(e:Event)=>{if(!ref.current?.contains(e.target as Node)&&!tooltip.current?.contains(e.target as Node))setOpen(false)};const escape=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false)};document.addEventListener('pointerdown',dismiss);document.addEventListener('keydown',escape);const close=()=>setOpen(false);window.addEventListener('resize',close);window.addEventListener('scroll',dismiss,true);return()=>{window.removeEventListener('resize',close);window.removeEventListener('scroll',dismiss,true);document.removeEventListener('pointerdown',dismiss);document.removeEventListener('keydown',escape)}},[open]);
 return <span className="mechanic-help" ref={ref} onPointerEnter={e=>{if(e.pointerType==='mouse')show()}} onPointerLeave={e=>{if(e.pointerType==='mouse'&&!tooltip.current?.contains(e.relatedTarget as Node))setOpen(false)}}>
 <button type="button" className="mechanic-info" aria-label={`About ${label}`} aria-expanded={open} aria-describedby={open?id:undefined} onClick={()=>open?setOpen(false):show()} onFocus={e=>{if(e.currentTarget.matches(':focus-visible'))show()}} onBlur={()=>setOpen(false)}>ⓘ</button>
 {open&&createPortal(<span ref={tooltip} role="tooltip" id={id} className="mechanic-tooltip" style={position} onPointerLeave={e=>{if(e.pointerType==='mouse'&&!ref.current?.contains(e.relatedTarget as Node))setOpen(false)}}><strong>{label}</strong>{explanations[topic]}</span>,document.body)}
 </span>;
}
